config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'riddles#index'
  resources :riddles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/riddle.rb
class Riddle < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/riddles_controller.rb
class RiddlesController < ApplicationController
  def index
    @riddle = Riddle.order("RANDOM()").first
  end

  def new
    @riddle = Riddle.new
  end

  def create
    Riddle.create(riddle_params)
    redirect_to root_path
  end

  private

  def riddle_params
    params.require(:riddle).permit(:riddle, :answer, :riddler)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/riddles_helper.rb
module RiddlesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Riddler</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="row">
      <div class="col-3">
        <%= link_to root_path, class: 'logo' do %>
          <div class="circle">
            <br />
            Riddle
            <br />
            Me
            <br />
            This
          </div>
        <% end %>
      </div>
      <div class="col-4 slogan">
        Storing your favorite riddles and questions since 2020!
      </div>
      <div class="col-5 links">
        <%= link_to 'Contribute', new_riddle_path %>
      </div>
    </header>

    <hr />

    <br class="clear" />

    <div class="container">
      <%= yield %>
    </div>

    <div class="footer">
      <div class="container">
        <div class="row">
          <div class="col-6">
            <%= link_to 'Give me more riddles!!', root_path, class: 'next-quote' %>
          </div>
        </div>
      </div>
    </div>

  </body>
</html>

app/views/riddles/index.html.erb
<h1><%= @riddle.riddle %></h1>
<h2><%= @riddle.answer %></h2>
<h3>- <%= @riddle.riddler %></h3>

app/views/riddles/new.html.erb
<h1>Add Your Riddle Here</h1>
<%= simple_form_for @riddle do |f| %>
  <%= f.input :riddle %>
  <%= f.input :answer %>
  <%= f.input :riddler %>
  <br />
  <%= f.submit 'Riddle Me This', class: 'btn btn-danger' %>
<% end %>